-- UnifiedRisk V12 / SECOPR
-- MIGRATE: Create Market Rotation Signal table (事实层)
-- Rationale: separate "market facts" from "strategy/backtest" signal.

-- Safe re-run: drop manually only if needed.

CREATE TABLE SECOPR.CN_SECTOR_ROTATION_MKT_SIGNAL_T (
    RUN_ID        VARCHAR2(64)   NOT NULL,
    SIGNAL_DATE   DATE           NOT NULL,
    SECTOR_TYPE   VARCHAR2(16)   NOT NULL,
    SECTOR_ID     NUMBER         NOT NULL,
    SECTOR_NAME   VARCHAR2(128)  NOT NULL,
    ACTION        VARCHAR2(8)    NOT NULL,  -- ENTER/WATCH/EXIT
    SIGNAL_SCORE  NUMBER,
    STRENGTH_TAG  VARCHAR2(32),
    REASONS_JSON  CLOB,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

ALTER TABLE SECOPR.CN_SECTOR_ROTATION_MKT_SIGNAL_T
  ADD CONSTRAINT PK_CN_SECTOR_ROT_MKT_SIGNAL PRIMARY KEY (RUN_ID, SIGNAL_DATE, SECTOR_TYPE, SECTOR_ID, ACTION);

CREATE INDEX SECOPR.IX_CN_SECTOR_ROT_MKT_SIGNAL_01
    ON SECOPR.CN_SECTOR_ROTATION_MKT_SIGNAL_T (SIGNAL_DATE, ACTION);

CREATE INDEX SECOPR.IX_CN_SECTOR_ROT_MKT_SIGNAL_02
    ON SECOPR.CN_SECTOR_ROTATION_MKT_SIGNAL_T (SECTOR_NAME);

-- Note:
-- - ACTION is part of PK to allow multiple tags per sector if needed (ENTER + WATCH).
-- - Report layer will group and show top signals.
