-- Optional Oracle table for Attack Window Case Log (DAY-level)
-- Schema: SECOPR
-- Note: Logger inserts DAY rows (one per run day), not per symbol.
CREATE TABLE SECOPR.CN_ATTACK_WINDOW_CASE_LOG_T (
    TRADE_DATE              DATE        NOT NULL,
    REPORT_KIND             VARCHAR2(16) NOT NULL,
    ATTACK_STATE            VARCHAR2(32),
    PREV_ATTACK_STATE       VARCHAR2(32),
    GATE_STATE              VARCHAR2(32),
    DRS_LEVEL               VARCHAR2(32),
    EXECUTION_BAND          VARCHAR2(32),
    TREND_STATE             VARCHAR2(32),
    ADV_RATIO               NUMBER(18,6),
    PCT_ABOVE_MA20          NUMBER(18,6),
    NEW_LOW_RATIO_PCT       NUMBER(18,6),
    AMOUNT_RATIO            NUMBER(18,6),
    PROXY_TOP20_AMOUNT_RATIO NUMBER(18,6),
    FAILURE_RATE_LEVEL      VARCHAR2(32),
    DECISION_REASONS        VARCHAR2(1000),
    CONSTRAINT_SUMMARY      VARCHAR2(1000),
    ALLOWED_ACTIONS         VARCHAR2(1000),
    FORBIDDEN_ACTIONS       VARCHAR2(1000),
    ROLLBACK_TRIGGERS_HIT    NUMBER(1),
    AUDIT_NOTES             VARCHAR2(1000),
    CREATED_AT              TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE INDEX SECOPR.IX_AW_CASE_LOG_DT ON SECOPR.CN_ATTACK_WINDOW_CASE_LOG_T(TRADE_DATE);
